# Problem Statement
Build a machine learning model to accurately predict whether or not the patients in the dataset have diabetes or not ?

=================================================================================

## 1. Import Necessary libraries

In [25]:
import pandas as pd
import keras
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import confusion_matrix,precision_score,recall_score,r2_score,accuracy_score,classification_report

## 2. Import Data

In [26]:
diabetes_data=pd.read_csv("diabetes.csv")
diabetes_data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

## 3. Data Understanding

In [27]:
diabetes_data.shape

(768, 9)

In [28]:
diabetes_data.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [29]:
diabetes_data.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

## 4. Data Preprocessing

In [30]:
X=diabetes_data.drop('Outcome',axis = 1)
y=diabetes_data [['Outcome']]

## 5. Model Building

In [31]:
from keras.models import Sequential
from keras.layers import Dense, Dropout

import warnings
warnings.filterwarnings("ignore")

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=12,stratify=y)

In [33]:
X_train.shape ,y_train.shape

((614, 8), (614, 1))

In [34]:
X_test.shape , y_test.shape

((154, 8), (154, 1))

In [35]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## HYPERPARAMETER TUNING

**List the Hyperparamaters we used so far ....**
1. Learning Rate
2. Epochs
3. Batches
4. Activation Functions
5. Optimizers
6. Loss Functions
7. Kernel Initializers

In [1]:
!pip install scikeras

Collecting scikeras
  Downloading scikeras-0.13.0-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: keras>=3.2.0 in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from scikeras) (3.12.2)
Requirement already satisfied: scikit-learn>=1.4.2 in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from scikeras) (1.7.2)
Requirement already satisfied: absl-py in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.2.0->scikeras) (2.4.0)
Requirement already satisfied: numpy in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.2.0->scikeras) (2.2.6)
Requirement already satisfied: rich in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.2.0->scikeras) (15.0.0)
Requirement already satisfied: namex in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.2.0->scikeras) (0.1.0)
Requirement already satisfied: h5py in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.2.0->scikeras) (3.14.0)
Requirement already satisfied: optree in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.2.0->scikeras) (0.19.1)
Requirement already satisfied: ml-dtypes in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.2.0->scikeras) (0.5.4)
Requirement already satisfied: packaging in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.2.0->scikeras) (26.0)
Requirement already satisfied: scipy>=1.8.0 in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn>=1.4.2->scikeras) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn>=1.4.2->scikeras) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn>=1.4.2->scikeras) (3.6.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from optree->keras>=3.2.0->scikeras) (4.15.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from rich->keras>=3.2.0->scikeras) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from rich->keras>=3.2.0->scikeras) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->scikeras) (0.1.2)
Downloading scikeras-0.13.0-py3-none-any.whl (26 kB)
Installing collected packages: scikeras
Successfully installed scikeras-0.13.0

WARNING: Ignoring invalid distribution -otebook (c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -otebook (c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -otebook (c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

## Hyperparameter all at once
**This process is computationally expensive.**

In [36]:
import numpy as np
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

from scikeras.wrappers import KerasClassifier
##I am building a neural network model using Keras Functional API, and I am using GridSearchCV with KerasClassifier to find the best
from sklearn.model_selection import GridSearchCV, KFold

In [37]:
def create_model(learning_rate=0.001, dropout_rate=0.0, activation_function='relu', init='glorot_uniform', neuron1=8, neuron2=4):

    model = Sequential()
    model.add(Dense(neuron1,input_shape=(8,),kernel_initializer=init,activation=activation_function))
    model.add(Dropout(dropout_rate))
    model.add(Dense(neuron2,kernel_initializer=init,activation=activation_function))
    model.add(Dropout(dropout_rate))
    model.add(Dense(1, activation='sigmoid'))
    
    optimizer = keras.optimizers.Adam(learning_rate=learning_rate)
    model.compile(loss='binary_crossentropy',optimizer=optimizer,metrics=['accuracy'])
    return model

In [38]:
model=KerasClassifier(model=create_model,verbose=1)

In [39]:
param_grid = {'model__learning_rate': [0.001, 0.01], 
#if its model_Lr = Just variable naming, but here it is model __ Learning_rate -> Navigate inside object
              'model__dropout_rate': [0.0, 0.2],
              'model__activation_function': ['relu', 'tanh'],
              'model__init': ['glorot_uniform', 'he_uniform'],
              'model__neuron1': [8, 16],
              'model__neuron2': [4, 8],
              'batch_size': [10, 20],
              'epochs': [10, 50]}

In [40]:
kfold=KFold(n_splits=3, shuffle=True, random_state=42)
grid=GridSearchCV(estimator=model,param_grid=param_grid,cv=kfold,verbose=10,n_jobs=-1)

In [41]:
grid_result = grid.fit(X_train, y_train)

Fitting 3 folds for each of 256 candidates, totalling 768 fits
WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
Epoch 1/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.3502 - loss: 0.8588
Epoch 2/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4072 - loss: 0.7983
Epoch 3/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4707 - loss: 0.7503
Epoch 4/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5358 - loss: 0.7117
Epoch 5/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5635 - loss: 0.6821
Epoch 6/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6205 - loss: 0.6563
Epoch 7/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6515 - loss: 0.6342
Epoch 8/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6743 - loss: 0.6132
Epoch 9/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6922 - loss: 0.5938
Epoch 10/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7215 - loss: 0.5756
Epoch 11/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7296 - loss: 0.5607
Epoch 12/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7313 - loss: 0.5475
Epoch 13/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7362 - loss: 0.5363
Epoch 14/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7427 - loss: 0.5274
Epoch 15/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7443 - loss: 0.5199
Epoch 16/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7524 - loss: 0.5134
Epoch 17/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7492 - loss: 0.5077
Epoch 18/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7524 - loss: 0.5025
Epoch 19/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7622 - loss: 0.4979
Epoch 20/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7606 - loss: 0.4938
Epoch 21/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7655 - loss: 0.4901
Epoch 22/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7655 - loss: 0.4867
Epoch 23/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7655 - loss: 0.4835
Epoch 24/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7655 - loss: 0.4808
Epoch 25/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7687 - loss: 0.4785
Epoch 26/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7655 - loss: 0.4764
Epoch 27/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7736 - loss: 0.4744
Epoch 28/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7736 - loss: 0.4727
Epoch 29/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7769 - loss: 0.4708
Epoch 30/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7818 - loss: 0.4693
Epoch 31/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7834 - loss: 0.4676
Epoch 32/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7834 - loss: 0.4663
Epoch 33/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7834 - loss: 0.4647
Epoch 34/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7801 - loss: 0.4637
Epoch 35/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7801 - loss: 0.4624
Epoch 36/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7785 - loss: 0.4613
Epoch 37/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7850 - loss: 0.4600
Epoch 38/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7834 - loss: 0.4589
Epoch 39/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7866 - loss: 0.4576
Epoch 40/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7850 - loss: 0.4567
Epoch 41/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7818 - loss: 0.4555
Epoch 42/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7850 - loss: 0.4549
Epoch 43/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7883 - loss: 0.4538
Epoch 44/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7850 - loss: 0.4528
Epoch 45/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7883 - loss: 0.4514
Epoch 46/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7899 - loss: 0.4506
Epoch 47/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7948 - loss: 0.4498
Epoch 48/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7948 - loss: 0.4490
Epoch 49/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8013 - loss: 0.4478
Epoch 50/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8029 - loss: 0.4472

In [46]:
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

means = grid_result.cv_results_["mean_test_score"]
stds = grid_result.cv_results_["std_test_score"]
params = grid_result.cv_results_["params"]

for mean, std, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, std, param))

Best: 0.781787 using {'batch_size': 20, 'epochs': 50, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4}
0.692093 (0.038828) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4}
0.757341 (0.007926) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8}
0.744325 (0.011647) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4}
0.765487 (0.010206) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8}
0.768747 (0.023168) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4}
0.747569 (0.014873) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8}
0.755667 (0.014406) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4}
0.741073 (0.017838) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8}
0.697107 (0.017646) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4}
0.741081 (0.037752) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8}
0.741065 (0.017031) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4}
0.734441 (0.037736) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8}
0.750845 (0.017855) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4}
0.757301 (0.017002) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8}
0.763813 (0.025593) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4}
0.736163 (0.006620) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8}
0.701937 (0.008588) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4}
0.713383 (0.039703) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8}
0.736139 (0.021291) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4}
0.739399 (0.008732) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8}
0.765447 (0.020989) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4}
0.763845 (0.002082) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8}
0.754041 (0.029085) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4}
0.750805 (0.010744) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8}
0.672581 (0.025684) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4}
0.701945 (0.022295) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8}
0.708385 (0.039008) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4}
0.732871 (0.012788) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8}
0.752415 (0.014492) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4}
0.768739 (0.008950) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8}
0.745911 (0.008498) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4}
0.763845 (0.021914) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8}
0.741001 (0.025331) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4}
0.767105 (0.012079) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8}
0.750805 (0.018372) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4}
0.763877 (0.023023) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8}
0.745951 (0.017038) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4}
0.754105 (0.023009) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8}
0.767105 (0.012079) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4}
0.765479 (0.018159) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8}
0.752487 (0.026148) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4}
0.757349 (0.011773) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8}
0.773649 (0.015658) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4}
0.763861 (0.012484) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8}
0.757365 (0.028533) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4}
0.765527 (0.023767) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8}
0.742707 (0.022266) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4}
0.762251 (0.025298) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8}
0.760625 (0.017784) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4}
0.745927 (0.000586) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8}
0.754073 (0.025896) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4}
0.770397 (0.030848) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8}
0.762251 (0.022298) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4}
0.755723 (0.017051) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8}
0.760609 (0.020441) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4}
0.762259 (0.019976) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8}
0.713375 (0.011698) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4}
0.721569 (0.035379) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8}
0.737829 (0.035405) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4}
0.757357 (0.025040) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8}
0.765463 (0.014503) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4}
0.762211 (0.021972) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8}
0.750821 (0.022095) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4}
0.760601 (0.010199) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8}
0.768707 (0.022178) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4}
0.745967 (0.017752) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8}
0.762251 (0.019651) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4}
0.768723 (0.008457) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8}
0.727961 (0.023323) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4}
0.745919 (0.014516) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8}
0.729595 (0.029821) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4}
0.719855 (0.019036) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8}
0.750845 (0.013267) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4}
0.750813 (0.004024) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8}
0.765455 (0.007462) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4}
0.742691 (0.009509) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8}
0.723139 (0.005502) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4}
0.724757 (0.025894) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8}
0.724773 (0.019406) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4}
0.711717 (0.022291) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8}
0.767089 (0.028352) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4}
0.772031 (0.035447) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8}
0.758959 (0.002079) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4}
0.757373 (0.019154) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8}
0.749155 (0.016588) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4}
0.741033 (0.010752) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8}

In [47]:
result_df=pd.DataFrame(grid_result.cv_results_)
result_df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_batch_size,param_epochs,param_model__activation_function,param_model__dropout_rate,param_model__init,param_model__learning_rate,param_model__neuron1,param_model__neuron2,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,5.420794,0.226941,0.424477,0.035335,10,10,relu,0.0,glorot_uniform,0.001,8,4,"{'batch_size': 10, 'epochs': 10, 'model__activ...",0.717073,0.721951,0.637255,0.692093,0.038828,251
1,5.487623,0.298340,0.440336,0.022611,10,10,relu,0.0,glorot_uniform,0.001,8,8,"{'batch_size': 10, 'epochs': 10, 'model__activ...",0.760976,0.746341,0.764706,0.757341,0.007926,97
2,5.195574,0.061421,0.442054,0.034746,10,10,relu,0.0,glorot_uniform,0.001,16,4,"{'batch_size': 10, 'epochs': 10, 'model__activ...",0.741463,0.731707,0.759804,0.744325,0.011647,168
3,5.338018,0.072796,0.773343,0.542251,10,10,relu,0.0,glorot_uniform,0.001,16,8,"{'batch_size': 10, 'epochs': 10, 'model__activ...",0.770732,0.751220,0.774510,0.765487,0.010206,47
4,6.664513,0.129532,0.673626,0.140334,10,10,relu,0.0,glorot_uniform,0.010,8,4,"{'batch_size': 10, 'epochs': 10, 'model__activ...",0.790244,0.736585,0.779412,0.768747,0.023168,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,13.037474,0.227519,0.369462,0.048962,20,50,tanh,0.2,he_uniform,0.001,16,8,"{'batch_size': 20, 'epochs': 50, 'model__activ...",0.756098,0.746341,0.740196,0.747545,0.006547,159
252,12.737686,0.113533,0.389972,0.033418,20,50,tanh,0.2,he_uniform,0.010,8,4,"{'batch_size': 20, 'epochs': 50, 'model__activ...",0.756098,0.721951,0.764706,0.747585,0.018463,155
253,12.676629,0.276144,0.297352,0.024775,20,50,tanh,0.2,he_uniform,0.010,8,8,"{'batch_size': 20, 'epochs': 50, 'model__activ...",0.751220,0.721951,0.750000,0.741057,0.013519,181
254,11.557918,0.697282,0.226597,0.017984,20,50,tanh,0.2,he_uniform,0.010,16,4,"{'batch_size': 20, 'epochs': 50, 'model__activ...",0.746341,0.731707,0.774510,0.750853,0.017763,129
255,8.319484,0.959820,0.185433,0.023144,20,50,tanh,0.2,he_uniform,0.010,16,8,"{'batch_size': 20, 'epochs': 50, 'model__activ...",0.756098,0.736585,0.784314,0.758999,0.019593,85

In [48]:
result_df.to_csv("results.csv")

# THE END